// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3vkCMB88WxK9O0f254XvfCkqTy6D7LaM',
    appId: '1:255047024275:web:99042c44bfd1ebc0f15766',
    messagingSenderId: '255047024275',
    projectId: 'colorist-4b1a2',
    authDomain: 'colorist-4b1a2.firebaseapp.com',
    storageBucket: 'colorist-4b1a2.firebasestorage.app',
    measurementId: 'G-KMJLDTKW42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZn6QHHObopqdkCQXeHJTcQ0x0_tT2U54',
    appId: '1:255047024275:android:018453c1ed48a3c1f15766',
    messagingSenderId: '255047024275',
    projectId: 'colorist-4b1a2',
    storageBucket: 'colorist-4b1a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYhDonO-UV0Z2WAUOM5i2-bkRlVQeHuTo',
    appId: '1:255047024275:ios:61b130fc1eaa038ef15766',
    messagingSenderId: '255047024275',
    projectId: 'colorist-4b1a2',
    storageBucket: 'colorist-4b1a2.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYhDonO-UV0Z2WAUOM5i2-bkRlVQeHuTo',
    appId: '1:255047024275:ios:61b130fc1eaa038ef15766',
    messagingSenderId: '255047024275',
    projectId: 'colorist-4b1a2',
    storageBucket: 'colorist-4b1a2.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3vkCMB88WxK9O0f254XvfCkqTy6D7LaM',
    appId: '1:255047024275:web:c35bf147262d743bf15766',
    messagingSenderId: '255047024275',
    projectId: 'colorist-4b1a2',
    authDomain: 'colorist-4b1a2.firebaseapp.com',
    storageBucket: 'colorist-4b1a2.firebasestorage.app',
    measurementId: 'G-23EGYFG9WC',
  );
}
